// <auto-generated />
namespace BuySellOldBooks.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpdtUserModel29Nov : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdtUserModel29Nov));
        
        string IMigrationMetadata.Id
        {
            get { return "201411282310304_UpdtUserModel29Nov"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
