// <auto-generated />
namespace BuySellOldBooks.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updateRegForNickName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateRegForNickName));
        
        string IMigrationMetadata.Id
        {
            get { return "201412130805081_updateRegForNickName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
