// <auto-generated />
namespace BuySellOldBooks.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpdatUserTblModifDateProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatUserTblModifDateProp));
        
        string IMigrationMetadata.Id
        {
            get { return "201505110633473_UpdatUserTblModifDateProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
