// <auto-generated />
namespace BuySellOldBooks.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updtUsertblmodifydt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updtUsertblmodifydt));
        
        string IMigrationMetadata.Id
        {
            get { return "201505110601064_updtUsertblmodifydt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
