namespace BuySellOldBooks.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using BuySellOldBooks.Models;
    using System.Collections.Generic;

    internal sealed class Configuration : DbMigrationsConfiguration<BuySellOldBooks.DataAccessLayer.PustakContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(BuySellOldBooks.DataAccessLayer.PustakContext context)
        {
            //test data filled during development from here, although cities and catagories are still passing from here for production.

            //var books = new List<Book>
            //{
            //    new Book{ Title="Data Structures and Object Representation"                                         , Author="Sean Thompson"                            , Edition=1     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=190    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Advanced Computer System Architecture"                                             , Author="John Gemmelaro"                           , Edition=5     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=400    ,Review="Poor Condition"        ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Design and Analysis of Algorithm"                                                  , Author="Tom Cruse"                                , Edition=1     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=60     ,Review="Normal Condition"      ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Pattern Recognition and Application"                                               , Author="D. Ravichandran and Murli Manohar"        , Edition=4     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=120    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Advanced Operating System"                                                         , Author="Sonam Thakur"                             , Edition=1     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=150    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Computer Communications Network"                                                   , Author="Bill Gates"                               , Edition=1     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=980    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Neural Network and applications"                                                   , Author="Indira Nuyi"                              , Edition=1     , Category="Computers and Internet"                                 , Locality="Sector-53"                    , City="Noida"          ,State="Uttar Pradesh"  ,Price=65     ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Parallel Processing"                                                               , Author="Ratan lal tata"                           , Edition=1     , Category="Computers and Internet"                                 , Locality="Vijay Nagar, Single-Story"    , City="Delhi"          ,State="Delhi"          ,Price=560    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Automation Engineering"                                                            , Author="Tom Jim Karern"                           , Edition=1     , Category="Computers and Internet"                                 , Locality="Vijay Nagar, Single-Story"    , City="Delhi"          ,State="Delhi"          ,Price=654    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Mobile Computing"                                                                  , Author="Ansul Kumar Vajpayee"                     , Edition=1     , Category="Computers and Internet"                                 , Locality="Vijay Nagar, Single-Story"    , City="Delhi"          ,State="Delhi"          ,Price=20     ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Fuzzy Set Theory & Application"                                                    , Author="Anil Singh"                               , Edition=1     , Category="Computers and Internet"                                 , Locality="Vijay Nagar, Single-Story"    , City="Delhi"          ,State="Delhi"          ,Price=800    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Design Principles of Language Translator"                                          , Author="Bhartendu Sharma"                         , Edition=1     , Category="Computers and Internet"                                 , Locality="Mayur Vihar"                  , City="Delhi"          ,State="Delhi"          ,Price=350    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Space and storage management enhancements"                                         , Author="Manendar amarnath"                        , Edition=1     , Category="Computers and Internet"                                 , Locality="Mayur Vihar"                  , City="Delhi"          ,State="Delhi"          ,Price=80     ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="The oracle scheduler and the database resource manager"                            , Author="Zaamreen"                                 , Edition=1     , Category="Computers and Internet"                                 , Locality="Mayur Vihar"                  , City="Delhi"          ,State="Delhi"          ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="Installation, Server Configuration and Database Upgrades"                          , Author="Yuvraj Singh"                             , Edition=1     , Category="Computers and Internet"                                 , Locality="Mayur Vihar"                  , City="Delhi"          ,State="Delhi"          ,Price=60     ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-10-05")},
            //    new Book{ Title="The Meritorious Price of Our Redemption (1650)"                                    , Author="William Pynchon"                          , Edition=1     , Category="English"                                                , Locality="Lajpat Nagar"                 , City="Kanpur"         ,State="Uttar Pradesh"  ,Price=200    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-1-05")},
            //    new Book{ Title="A Message to Man and Humanity"                                                     , Author="Aleksandar Cvetkovic"                     , Edition=1     , Category="English"                                                , Locality="Tilak Nagar"                  , City="Kanpur"         ,State="Uttar Pradesh"  ,Price=450    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-2-06")},
            //    new Book{ Title="Mirror of the Polish Crown"                                                        , Author="William S. Burroughs"                     , Edition=1     , Category="English"                                                , Locality="Pared"                        , City="Kanpur"         ,State="Uttar Pradesh"  ,Price=100    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-8-11")},
            //    new Book{ Title="Moll Flanders or The Fortunes and Misfortunes of the Famous Moll Flanders (1722)"  , Author="Daniel Defoe"                             , Edition=1     , Category="English"                                                , Locality="Char Bagh"                    , City="Lucknow"        ,State="Uttar Pradesh"  ,Price=60     ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-4-04")},
            //    new Book{ Title="The Nickel-Plated-Feet Gang During the Occupation"                                 , Author="Successors of Louis Forton (1879–1934)"   , Edition=1     , Category="English"                                                , Locality="Husainabaad"                  , City="Lucknow"        ,State="Uttar Pradesh"  ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},

            //    new Book{ Title="The Test Book Title 01"                                                            , Author="Test Author 01"                           , Edition=1     , Category="Psychology"                                             , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 02"                                                            , Author="Test Author 02"                           , Edition=2     , Category="Psychology"                                             , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=400    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 03"                                                            , Author="Test Author 03"                           , Edition=3     , Category="Psychology"                                             , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 04"                                                            , Author="Test Author 04"                           , Edition=4     , Category="Psychology"                                             , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 05"                                                            , Author="Test Author 05"                           , Edition=5     , Category="Psychology"                                             , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=450    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 06"                                                            , Author="Test Author 06"                           , Edition=6     , Category="Magazines"                                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 07"                                                            , Author="Test Author 07"                           , Edition=7     , Category="Magazines"                                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 08"                                                            , Author="Test Author 08"                           , Edition=8     , Category="Magazines"                                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 09"                                                            , Author="Test Author 09"                           , Edition=1     , Category="Magazines"                                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=700    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 10"                                                            , Author="Test Author 10"                           , Edition=2     , Category="Magazines"                                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 11"                                                            , Author="Test Author 11"                           , Edition=3     , Category="Music, and Entertainment"                               , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=560    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 12"                                                            , Author="Test Author 12"                           , Edition=4     , Category="Music, and Entertainment"                               , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 13"                                                            , Author="Test Author 13"                           , Edition=5     , Category="Music, and Entertainment"                               , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=100    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 14"                                                            , Author="Test Author 14"                           , Edition=6     , Category="Music, and Entertainment"                               , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 15"                                                            , Author="Test Author 15"                           , Edition=7     , Category="Music, and Entertainment"                               , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 16"                                                            , Author="Test Author 16"                           , Edition=8     , Category="Religion and Spirituality"                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 17"                                                            , Author="Test Author 17"                           , Edition=1     , Category="Religion and Spirituality"                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 18"                                                            , Author="Test Author 18"                           , Edition=2     , Category="Religion and Spirituality"                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 19"                                                            , Author="Test Author 19"                           , Edition=3     , Category="Religion and Spirituality"                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 20"                                                            , Author="Test Author 20"                           , Edition=4     , Category="Religion and Spirituality"                              , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 21"                                                            , Author="Test Author 21"                           , Edition=5     , Category="Travel"                                                 , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=140    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 22"                                                            , Author="Test Author 22"                           , Edition=6     , Category="Travel"                                                 , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 23"                                                            , Author="Test Author 23"                           , Edition=7     , Category="Travel"                                                 , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 24"                                                            , Author="Test Author 24"                           , Edition=8     , Category="Travel"                                                 , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 25"                                                            , Author="Test Author 25"                           , Edition=9     , Category="Travel"                                                 , Locality="Harishankar Puram"            , City="Gwalior"        ,State="Madhya Pradesh",Price=250    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},

            //    new Book{ Title="The Test Book Title 26"                                                            , Author="Test Author 26"                           , Edition=1     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bangalore"          ,State="Uttar Pradesh" ,Price=100    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 27"                                                            , Author="Test Author 27"                           , Edition=2     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bangalore"          ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 28"                                                            , Author="Test Author 28"                           , Edition=3     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 29"                                                            , Author="Test Author 29"                           , Edition=4     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 30"                                                            , Author="Test Author 30"                           , Edition=5     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 31"                                                            , Author="Test Author 31"                           , Edition=6     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 32"                                                            , Author="Test Author 32"                           , Edition=7     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=200    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 33"                                                            , Author="Test Author 33"                           , Edition=8     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 34"                                                            , Author="Test Author 34"                           , Edition=1     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=777    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 35"                                                            , Author="Test Author 35"                           , Edition=2     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=444    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 36"                                                            , Author="Test Author 36"                           , Edition=3     , Category="Social Science"                                         , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 37"                                                            , Author="Test Author 37"                           , Edition=4     , Category="Social Science"                                         , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 38"                                                            , Author="Test Author 38"                           , Edition=5     , Category="Social Science"                                         , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=111    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 39"                                                            , Author="Test Author 39"                           , Edition=6     , Category="Social Science"                                         , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 40"                                                            , Author="Test Author 40"                           , Edition=7     , Category="Social Science"                                         , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 41"                                                            , Author="Test Author 41"                           , Edition=7     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 42"                                                            , Author="Test Author 42"                           , Edition=8     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=601    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 43"                                                            , Author="Test Author 43"                           , Edition=9     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 44"                                                            , Author="Test Author 44"                           , Edition=4     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 45"                                                            , Author="Test Author 45"                           , Edition=5     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=400    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 46"                                                            , Author="Test Author 46"                           , Edition=6     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 47"                                                            , Author="Test Author 47"                           , Edition=6     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 48"                                                            , Author="Test Author 48"                           , Edition=7     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=222    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 49"                                                            , Author="Test Author 49"                           , Edition=8     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="The Test Book Title 50"                                                            , Author="Test Author 50"                           , Edition=9     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bangalore"         ,State="Uttar Pradesh" ,Price=350    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},

            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.5 26"                                                         , Author="Wan Henselmen 26"                            , Edition=1     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=100    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 2.7"                                                            , Author="Wan Henselmen 27"                            , Edition=2     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 2.8"                                                            , Author="Wann Henselman 28"                           , Edition=3     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 2.9"                                                            , Author="Wann Henselman 29"                           , Edition=4     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.0"                                                            , Author="Wann Henselman 30"                           , Edition=5     , Category="Tax and Accounting"                                     , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.1"                                                            , Author="Wann Henselman 31"                           , Edition=6     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.2"                                                            , Author="Wann Henselman 32"                           , Edition=7     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=200    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.3"                                                            , Author="Wann Henselman 33"                           , Edition=8     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.4"                                                            , Author="Wann Henselman 34"                           , Edition=1     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=777    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.5"                                                            , Author="Wann Henselman 35"                           , Edition=2     , Category="Sports and Adventure"                                   , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=444    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.6"                                                            , Author="Wann Henselman 36"                           , Edition=3     , Category="Social Science"                                         , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.7"                                                            , Author="Wann Henselman 37"                           , Edition=4     , Category="Social Science"                                         , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.8"                                                            , Author="Wann Henselman 38"                           , Edition=5     , Category="Social Science"                                         , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=111    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 3.9"                                                            , Author="Wann Henselman 39"                           , Edition=6     , Category="Social Science"                                         , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.0"                                                            , Author="Wann Henselman 40"                           , Edition=7     , Category="Social Science"                                         , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.1"                                                            , Author="Wann Henselman 41"                           , Edition=7     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.2"                                                            , Author="Wann Henselman 42"                           , Edition=8     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=601    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.3"                                                            , Author="Wann Henselman 43"                           , Edition=9     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.4"                                                            , Author="Wann Henselman 44"                           , Edition=4     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.5"                                                            , Author="Wann Henselman 45"                           , Edition=5     , Category="Self-Help"                                              , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=400    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.6"                                                            , Author="Wann Henselman 46"                           , Edition=6     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.7"                                                            , Author="Wann Henselman 47"                           , Edition=6     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.8"                                                            , Author="Wann Henselman 48"                           , Edition=7     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=222    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 4.9"                                                            , Author="Wann Henselman 49"                           , Edition=8     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=600    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")},
            //    new Book{ Title="Master in Package Manager Console .Net Framework 5.0"                                                            , Author="Wann Henselman 50"                           , Edition=9     , Category="Science and Technology"                                 , Locality="IT City"                  , City="Bhopal"         ,State="Uttar Pradesh" ,Price=350    ,Review="Very Good Condition"   ,IsActive=true    ,EntryDateTime=DateTime.Parse("2010-5-12")}
            //};
            //books.ForEach(s => context.Books.AddOrUpdate(p => p.BookID, s));
            //context.SaveChanges();

            var categories = new List<Category>
            {
                new Category{CategoryName="Architecture"},
                new Category{CategoryName="Arts and Design"},
                new Category{CategoryName="Astrology"},
                new Category{CategoryName="Aviation and Astronomy"},
                new Category{CategoryName="Ayurveda"},
                new Category{CategoryName="Biographies"},
                new Category{CategoryName="Business and Management"},
                new Category{CategoryName="Children and Teens"},
                new Category{CategoryName="Computers and Internet"},
                new Category{CategoryName="Cooking Food and Wine"},
                new Category{CategoryName="Economics and Finance"},
                new Category{CategoryName="Engineering"},
                new Category{CategoryName="English"},
                new Category{CategoryName="Environment"},
                new Category{CategoryName="Examination"},
                new Category{CategoryName="Family and Relationships"},
                new Category{CategoryName="Fashion"},
                new Category{CategoryName="Fiction and Literature"},
                new Category{CategoryName="General Knowledge"},
                new Category{CategoryName="Geography, Maps and Atlases"},
                new Category{CategoryName="Health and Fitness"},
                new Category{CategoryName="History and Politics"},
                new Category{CategoryName="Home and Garden"},
                new Category{CategoryName="Homeopathy"},
                new Category{CategoryName="Hospitality"},
                new Category{CategoryName="Humor"},
                new Category{CategoryName="IIT-JEE"},
                new Category{CategoryName="Languages"},
                new Category{CategoryName="Law"},
                new Category{CategoryName="Magazines"},
                new Category{CategoryName="Marketing and Advertising"},
                new Category{CategoryName="Media and Journalism"},
                new Category{CategoryName="Medical Books"},
                new Category{CategoryName="Music, and Entertainment"},
                new Category{CategoryName="Non-Fiction"},
                new Category{CategoryName="Others"},
                new Category{CategoryName="Photography"},
                new Category{CategoryName="Philosophy"},
                new Category{CategoryName="Poetry"},
                new Category{CategoryName="Psychology"},
                new Category{CategoryName="Quiz and Puzzles"},
                new Category{CategoryName="References"},
                new Category{CategoryName="Religion and Spirituality"},
                new Category{CategoryName="School Books"},
                new Category{CategoryName="Science and Technology"},
                new Category{CategoryName="Self-Help"},
                new Category{CategoryName="Social Science"},
                new Category{CategoryName="Sports and Adventure"},
                new Category{CategoryName="Tax and Accounting"},
                new Category{CategoryName="Travel"}
            };
            categories.ForEach(s => context.Categories.AddOrUpdate(p => p.CategoryID, s));
            context.SaveChanges();

            var city = new List<City>
            {
                new City{CityName="Agartala"},
                new City{CityName="Agra"},
                new City{CityName="Ahmedabad"},
                new City{CityName="Ajmer"},
                new City{CityName="Aligarh"},
                new City{CityName="Allahabad"},
                new City{CityName="Alwar"},
                new City{CityName="Ambala"},
                new City{CityName="Amritsar"},
                new City{CityName="Anantapur"},
                new City{CityName="Aurangabad"},
                new City{CityName="Bahadurgarh"},
                new City{CityName="Bangalore"},
                new City{CityName="Bareilly"},
                new City{CityName="Bellary"},
                new City{CityName="Bharuch"},
                new City{CityName="Bhatinda"},
                new City{CityName="Bhavnagar"},
                new City{CityName="Bhopal"},
                new City{CityName="Bhubaneshwar"},
                new City{CityName="Bikaner"},
                new City{CityName="Bokaro"},
                new City{CityName="Calicut"},
                new City{CityName="Chandigarh"},
                new City{CityName="Chennai"},
                new City{CityName="Coimbatore"},
                new City{CityName="Dalhousie"},
                new City{CityName="Dehradun"},
                new City{CityName="Delhi"},
                new City{CityName="Dhanbad"},
                new City{CityName="Dharwad"},
                new City{CityName="Dindigul"},
                new City{CityName="Durgapur"},
                new City{CityName="East Godavari"},
                new City{CityName="Ernakulam"},
                new City{CityName="Erode"},
                new City{CityName="Faizabad"},
                new City{CityName="Faridabad"},
                new City{CityName="Gandhinagar"},
                new City{CityName="Ghaziabad"},
                new City{CityName="Goa"},
                new City{CityName="Gorakhpur"},
                new City{CityName="Greater Noida"},
                new City{CityName="Gulbarga"},
                new City{CityName="Gurgaon"},
                new City{CityName="Guwahati"},
                new City{CityName="Gwalior"},
                new City{CityName="Haldia"},
                new City{CityName="Haldwani"},
                new City{CityName="Hapur"},
                new City{CityName="Haridwar"},
                new City{CityName="Hissar"},
                new City{CityName="Hosur"},
                new City{CityName="Hubli"},
                new City{CityName="Hyderabad"},
                new City{CityName="Indore"},
                new City{CityName="Jabalpur"},
                new City{CityName="Jaipur"},
                new City{CityName="Jalandhar"},
                new City{CityName="Jalgaon"},
                new City{CityName="Jammu"},
                new City{CityName="Jamnagar"},
                new City{CityName="Jamshedpur"},
                new City{CityName="Jodhpur"},
                new City{CityName="Junagadh"},
                new City{CityName="Kanpur"},
                new City{CityName="Karimnagar"},
                new City{CityName="Karnal"},
                new City{CityName="Kharagpur"},
                new City{CityName="Kochi"},
                new City{CityName="Kolar"},
                new City{CityName="Kolhapur"},
                new City{CityName="Kolkata"},
                new City{CityName="Kollam"},
                new City{CityName="Kota"},
                new City{CityName="Kottayam"},
                new City{CityName="Kurukshetra"},
                new City{CityName="Lucknow"},
                new City{CityName="Ludhiana"},
                new City{CityName="Madurai"},
                new City{CityName="Mangalore"},
                new City{CityName="Margao"},
                new City{CityName="Mathura"},
                new City{CityName="Meerut"},
                new City{CityName="Moga"},
                new City{CityName="Mohali"},
                new City{CityName="Mumbai"},
                new City{CityName="Mysore"},
                new City{CityName="Nagpur"},
                new City{CityName="Nasik"},
                new City{CityName="Nellore"},
                new City{CityName="Noida"},
                new City{CityName="Palakkad"},
                new City{CityName="Panaji"},
                new City{CityName="Panchkula"},
                new City{CityName="Panipat"},
                new City{CityName="Pathankot"},
                new City{CityName="Patiala"},
                new City{CityName="Patna"},
                new City{CityName="Pondicherry"},
                new City{CityName="Pune"},
                new City{CityName="Raipur"},
                new City{CityName="Rajkot"},
                new City{CityName="Ranchi"},
                new City{CityName="Rohtak"},
                new City{CityName="Roorkee"},
                new City{CityName="Rourkela"},
                new City{CityName="Rudrapur"},
                new City{CityName="Salem"},
                new City{CityName="Secunderabad"},
                new City{CityName="Shillong"},
                new City{CityName="SIlchar"},
                new City{CityName="Siliguri"},
                new City{CityName="Solan"},
                new City{CityName="Sonipat"},
                new City{CityName="Srikakulam"},
                new City{CityName="Srinagar"},
                new City{CityName="Surat"},
                new City{CityName="Thrissur"},
                new City{CityName="Tirupati"},
                new City{CityName="Tirupur"},
                new City{CityName="Trichy"},
                new City{CityName="Trivandrum"},
                new City{CityName="Udaipur"},
                new City{CityName="Ujjain"},
                new City{CityName="Vadodara"},
                new City{CityName="Varanasi"},
                new City{CityName="Vellore"},
                new City{CityName="Vijayawada"},
                new City{CityName="Vishakhapatnam"},
                new City{CityName="Warangal"}
            };
            city.ForEach(s => context.Cities.AddOrUpdate(p => p.CityID, s));
            context.SaveChanges();
        }
        
            
    }
}
